services:
  time:
    image: mcp/time
  oracle:
    image: mochoa/mcp-oracle
    command: ["host.docker.internal:1521/freepdb1"]
    environment:
      - ORACLE_USER=scott
      - ORACLE_PASSWORD=tiger
